services:
  weather-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-bot-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data:ro
      - weather-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - weather-network

volumes:
  weather-logs:
    driver: local

networks:
  weather-network:
    driver: bridge
