from typing import Dict, List

# List of 100+ major cities worldwide for weather monitoring
MAJOR_CITIES: List[str] = [
    # North America
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Long Beach",
    "Colorado Springs",
    "Raleigh",
    "Miami",
    "Virginia Beach",
    "Omaha",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Arlington",
    "Tampa",
    "New Orleans",
    "Wichita",
    "Cleveland",
    "Bakersfield",
    # Canada
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Kitchener",
    # Mexico
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Juárez",
    "Zapopan",
    "Nezahualcóyotl",
    "Chihuahua",
    # South America
    "São Paulo",
    "Rio de Janeiro",
    "Buenos Aires",
    "Lima",
    "Bogotá",
    "Santiago",
    "Caracas",
    "Salvador",
    "Brasília",
    "Fortaleza",
    "Guayaquil",
    "Quito",
    "La Paz",
    "Santa Cruz",
    "Montevideo",
    "Asunción",
    "Medellín",
    "Cali",
    # Europe
    "London",
    "Berlin",
    "Madrid",
    "Rome",
    "Paris",
    "Hamburg",
    "Barcelona",
    "Munich",
    "Milan",
    "Prague",
    "Sofia",
    "Copenhagen",
    "Stockholm",
    "Helsinki",
    "Oslo",
    "Warsaw",
    "Kraków",
    "Budapest",
    "Vienna",
    "Zurich",
    "Amsterdam",
    "Brussels",
    "Dublin",
    "Lisbon",
    "Athens",
    "Istanbul",
    "Moscow",
    "Saint Petersburg",
    "Kiev",
    "Minsk",
    "Riga",
    "Vilnius",
    "Tallinn",
    "Belgrade",
    "Zagreb",
    "Ljubljana",
    "Sarajevo",
    "Skopje",
    "Tirana",
    "Bucharest",
    # Asia
    "Tokyo",
    "Delhi",
    "Shanghai",
    "Dhaka",
    "São Paulo",
    "Cairo",
    "Mexico City",
    "Beijing",
    "Mumbai",
    "Osaka",
    "Karachi",
    "Chongqing",
    "Istanbul",
    "Buenos Aires",
    "Kolkata",
    "Manila",
    "Lagos",
    "Rio de Janeiro",
    "Tianjin",
    "Kinshasa",
    "Guangzhou",
    "Los Angeles",
    "Moscow",
    "Shenzhen",
    "Lahore",
    "Bangalore",
    "Paris",
    "Bogotá",
    "Jakarta",
    "Chennai",
    "Lima",
    "Bangkok",
    "Seoul",
    "Nagoya",
    "Hyderabad",
    "London",
    "Tehran",
    "Chicago",
    "Chengdu",
    "Nanjing",
    "Wuhan",
    "Ho Chi Minh City",
    "Luanda",
    "Ahmedabad",
    "Kuala Lumpur",
    "Xi'an",
    "Hong Kong",
    "Dongguan",
    "Hangzhou",
    "Foshan",
    "Shenyang",
    "Riyadh",
    "Baghdad",
    "Santiago",
    "Surat",
    "Madrid",
    "Suzhou",
    "Pune",
    "Harbin",
    "Houston",
    "Dallas",
    "Toronto",
    "Dar es Salaam",
    "Miami",
    "Belo Horizonte",
    "Singapore",
    "Philadelphia",
    "Atlanta",
    "Fukuoka",
    "Khartoum",
    "Barcelona",
    "Johannesburg",
    "Saint Petersburg",
    "Qingdao",
    "Dalian",
    "Washington",
    "Yangon",
    "Alexandria",
    "Jinan",
    "Guadalajara",
    # Africa
    "Lagos",
    "Cairo",
    "Kinshasa",
    "Luanda",
    "Nairobi",
    "Mogadishu",
    "Rabat",
    "Addis Ababa",
    "Khartoum",
    "Johannesburg",
    "Dar es Salaam",
    "Kano",
    "Ibadan",
    "Dakar",
    "Bamako",
    "Conakry",
    "Freetown",
    "Monrovia",
    "Abidjan",
    "Accra",
    "Lomé",
    "Cotonou",
    "Ouagadougou",
    "Niamey",
    "N'Djamena",
    "Bangui",
    "Brazzaville",
    "Libreville",
    "Malabo",
    "São Tomé",
    "Luanda",
    "Windhoek",
    "Gaborone",
    "Maseru",
    "Mbabane",
    "Maputo",
    "Antananarivo",
    "Port Louis",
    "Victoria",
    # Oceania
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Newcastle",
    "Canberra",
    "Sunshine Coast",
    "Wollongong",
    "Geelong",
    "Townsville",
    "Cairns",
    "Darwin",
    "Toowoomba",
    "Ballarat",
    "Bendigo",
    "Albury",
    "Launceston",
    "Mackay",
    "Rockhampton",
    "Bunbury",
    "Bundaberg",
    "Coffs Harbour",
    "Wagga Wagga",
    "Hervey Bay",
    "Mildura",
    "Shepparton",
    "Port Macquarie",
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Napier",
    "Hastings",
    "Dunedin",
    "Palmerston North",
    "Nelson",
    "Rotorua",
    "New Plymouth",
    "Whangarei",
    "Invercargill",
]


def get_cities_list(limit: int = None) -> List[str]:
    """
    Get the list of cities to monitor.

    Args:
        limit: Maximum number of cities to return. If None, return all cities.

    Returns:
        List of city names
    """
    if limit is None:
        return MAJOR_CITIES.copy()
    return MAJOR_CITIES[:limit]


def get_cities_by_region() -> Dict[str, List[str]]:
    """
    Get cities organized by region.

    Returns:
        Dictionary mapping region names to lists of cities
    """
    return {
        "North America": MAJOR_CITIES[0:53],
        "Canada": MAJOR_CITIES[53:63],
        "Mexico": MAJOR_CITIES[63:73],
        "South America": MAJOR_CITIES[73:91],
        "Europe": MAJOR_CITIES[91:131],
        "Asia": MAJOR_CITIES[131:211],
        "Africa": MAJOR_CITIES[211:241],
        "Oceania": MAJOR_CITIES[241:],
    }

